/**
 * Every texture the client loads, in one place, from the SITE ROOT.
 *
 * **The path is the whole reason this module exists.** A leading slash rather
 * than `./`, for the reason the wasm is loaded that way and spelled out where
 * it is: the console is served from `/play/<id>` as well as from `/`, and
 * `./ember.png` there is `/play/ember.png`, which the shell route answers with
 * the index page. A texture handed HTML does not throw. The load quietly
 * fails, the material keeps a normal map with no pixels in it, three.js then
 * samples an empty texture so every fragment gets a garbage normal, and the
 * hull draws as flat dark paint: exactly what a finish that was never applied
 * looks like. The ember atlas and all nine armour finishes shipped dead that
 * way, on a branch whose commit message said they were live.
 *
 * `main.ts` already loaded the wasm absolutely and said why on the line above
 * it, and three later loads did not copy the lesson. So there is one loader
 * now: the map, the shipyard and the schematic all ask here, and a fourth
 * caller cannot spell the path its own way.
 *
 * Loaded on demand and kept. A skirmish wants one or two finishes, not the
 * whole set, and the shipyard wants whichever one the design being edited
 * wears.
 */
import * as THREE from 'three';

/** From the root, always. See the note above. */
const at = (name: string): string => `/${name}`;

/**
 * The ember atlas, one for every wound on every ship.
 *
 * A file rather than something drawn at runtime (GUIDELINES 3), generated by
 * `tools/make_ember_texture.py`. NearestFilter on purpose: the hull is a
 * lattice of cells and its damage should look cut out of the same lattice, so
 * a smoothed crack would be the one soft thing on a ship made of blocks.
 * No mipmaps, because a mip of an atlas blends the tiles into each other.
 */
let emberMap: THREE.Texture | null = null;
export function ember(): THREE.Texture {
  if (!emberMap) {
    emberMap = new THREE.TextureLoader().load(at('ember.png'));
    emberMap.magFilter = THREE.NearestFilter;
    emberMap.minFilter = THREE.LinearFilter;
    emberMap.generateMipmaps = false;
    emberMap.colorSpace = THREE.SRGBColorSpace;
  }
  return emberMap;
}

/**
 * An armour finish, as a tiling normal map.
 *
 * `smooth` is no texture at all rather than a flat one: it is the same picture
 * for no bytes and no sample.
 *
 * Unlike the ember these DO get mipmaps and linear filtering, because a finish
 * is seen at every range from a hull filling the screen to four pixels of it,
 * and an unmipped normal map at map range is a field of noise that never
 * settles.
 */
const finishMaps = new Map<string, THREE.Texture>();
export function finishMap(key: string): THREE.Texture | null {
  if (key === 'smooth') return null;
  const had = finishMaps.get(key);
  if (had) return had;
  const t = new THREE.TextureLoader().load(at(`surf/armour_${key}_n.png`));
  t.wrapS = t.wrapT = THREE.RepeatWrapping;
  t.colorSpace = THREE.NoColorSpace;
  t.anisotropy = 4;
  finishMaps.set(key, t);
  return t;
}

/**
 * What MACHINERY is made of, as against plating.
 *
 * A drive bell and an armour panel are not the same surface, and drawing both
 * in the hull's finish made a ship one material with parts drawn on it. Every
 * cell that belongs to a placement wears this instead: greebled, which is a
 * field of small boxes and pipes and is what the inside of a ship looks like.
 *
 * One finish for all of them rather than one per module kind. A player can
 * already tell a drive from a gun by its COLOUR, which is the shipyard's whole
 * legend; what they could not tell was machinery from plate, and that is one
 * distinction, not nine.
 */
export const PART_FINISH = 'greeble';
export function partMap(): THREE.Texture | null { return finishMap(PART_FINISH); }

/**
 * How many variants each window decal was generated with.
 *
 * Packed side by side in one image rather than as separate files: a decal has
 * to TILE once per cell across a greedy quad, and repeat wrapping repeats a
 * whole image rather than one tile of it, so a strip is sampled by offsetting
 * into it instead. Cabins are the reason this exists: a run of quarters down a
 * flank with the same panes lit in every one of them reads as a repeating
 * panel rather than as a ship with people in it.
 *
 * Mirrors the counts in `tools/make_surface_textures.py`, and has to: the
 * offset per cell is 1/N of the image, so a wrong N samples across a seam.
 */
export const WINDOW_VARIANTS: Readonly<Record<string, number>> = {
  porthole: 1, panes: 7, strip: 5, bridge: 1, beacons: 1, hangar: 1,
};

/**
 * One window decal, as the three maps it takes to draw glass.
 *
 * Emission alone cannot do it. Emission only ADDS, so an unlit pane over hull
 * paint is hull paint, which is how a cabin came out the same shade as the
 * plating around it and one window looked missing altogether. The COLOUR map
 * is what makes glass dark: it multiplies the paint down to almost nothing
 * where the pane is and leaves the frame alone. Then emission lights the panes
 * that are on, and the normal seats the whole thing into the plate.
 */
export interface WindowMaps {
  readonly colour: THREE.Texture;
  readonly emissive: THREE.Texture;
  readonly normal: THREE.Texture;
  readonly variants: number;
}

const windowMaps = new Map<string, WindowMaps>();
export function windowMap(key: string): WindowMaps | null {
  const had = windowMaps.get(key);
  if (had) return had;
  const variants = WINDOW_VARIANTS[key];
  if (!variants) return null;
  const load = (suffix: string, srgb: boolean): THREE.Texture => {
    const t = new THREE.TextureLoader().load(at(`surf/window_${key}_${suffix}.png`));
    // Clamped, not repeated. The UVs a mesher writes for a window already
    // point at one variant's slice of the strip, and wrapping would let a
    // rounding error at the edge of a cell sample the neighbouring variant.
    t.wrapS = t.wrapT = THREE.ClampToEdgeWrapping;
    t.colorSpace = srgb ? THREE.SRGBColorSpace : THREE.NoColorSpace;
    t.anisotropy = 4;
    return t;
  };
  const maps: WindowMaps = {
    colour: load('c', true),
    emissive: load('e', true),
    normal: load('n', false),
    variants,
  };
  windowMaps.set(key, maps);
  return maps;
}

/**
 * The material a window decal is drawn with.
 *
 * `vertexColors` carries the hull's own paint and `map` multiplies it, so the
 * FRAME round a pane stays the colour of the plating it is cut into and the
 * glass goes almost black. Emission is added on top and is the only part that
 * survives with no light on it, which is what makes a lit cabin read across
 * the map at night. `emissiveIntensity` above one on purpose: the bloom pass
 * thresholds just under 1 after tone mapping, so a window has to clear that to
 * glow rather than merely to be bright.
 *
 * One material per KIND, shared by every ship: the decal is the same and the
 * per hull difference is in the vertex colours and the UVs.
 */
const windowMats = new Map<string, THREE.MeshStandardMaterial>();
export function windowMaterial(key: string): THREE.MeshStandardMaterial | null {
  const had = windowMats.get(key);
  if (had) return had;
  const maps = windowMap(key);
  if (!maps) return null;
  const mat = new THREE.MeshStandardMaterial({
    vertexColors: true,
    map: maps.colour,
    emissiveMap: maps.emissive,
    emissive: 0xffffff,
    emissiveIntensity: 1.6,
    normalMap: maps.normal,
    metalness: 0.15,
    roughness: 0.35,
    dithering: true,
  });
  windowMats.set(key, mat);
  return mat;
}

/**
 * What a metal reflects.
 *
 * Metalness with no environment renders BLACK, so any view that draws a hull
 * with the design's own metalness needs one of these or a bare alloy comes out
 * as a hole in the picture. The map has a baked nebula and uses that; the
 * shipyard and the schematic are indoor views with no sky, so they get this
 * strip: an equirectangular gradient whose two ends are the sky and ground
 * colours their own hemisphere light already uses, which is why a reflection
 * agrees with the lighting rather than arguing with it.
 *
 * PMREM'd once and shared. The generator needs a renderer, so the caller hands
 * one over; the result is cached because two views asking for it should not
 * pay for it twice.
 */
let envMap: THREE.Texture | null = null;
let envPending = false;
export function studioEnv(
  renderer: THREE.WebGLRenderer, onReady: (t: THREE.Texture) => void,
): void {
  if (envMap) { onReady(envMap); return; }
  if (envPending) return;
  envPending = true;
  new THREE.TextureLoader().load(at('surf/env.png'), tex => {
    tex.mapping = THREE.EquirectangularReflectionMapping;
    tex.colorSpace = THREE.SRGBColorSpace;
    const pmrem = new THREE.PMREMGenerator(renderer);
    envMap = pmrem.fromEquirectangular(tex).texture;
    pmrem.dispose();
    tex.dispose();
    envPending = false;
    onReady(envMap);
  }, undefined, () => { envPending = false; });
}
